//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.02 at 06:56:52 PM CEST 
//


package practricaswss.documento.factura;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttachmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttachmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AttachmentCompressionAlgorithm" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}AttachmentCompressionAlgorithmType" minOccurs="0"/>
 *         &lt;element name="AttachmentFormat" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}AttachmentFormatType"/>
 *         &lt;element name="AttachmentEncoding" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}AttachmentEncodingType" minOccurs="0"/>
 *         &lt;element name="AttachmentDescription" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}TextMax2500Type" minOccurs="0"/>
 *         &lt;element name="AttachmentData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttachmentType", propOrder = {
    "attachmentCompressionAlgorithm",
    "attachmentFormat",
    "attachmentEncoding",
    "attachmentDescription",
    "attachmentData"
})
public class AttachmentType {

    @XmlElement(name = "AttachmentCompressionAlgorithm")
    @XmlSchemaType(name = "string")
    protected AttachmentCompressionAlgorithmType attachmentCompressionAlgorithm;
    @XmlElement(name = "AttachmentFormat", required = true)
    @XmlSchemaType(name = "string")
    protected AttachmentFormatType attachmentFormat;
    @XmlElement(name = "AttachmentEncoding")
    @XmlSchemaType(name = "string")
    protected AttachmentEncodingType attachmentEncoding;
    @XmlElement(name = "AttachmentDescription")
    protected String attachmentDescription;
    @XmlElement(name = "AttachmentData", required = true)
    protected String attachmentData;

    /**
     * Gets the value of the attachmentCompressionAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentCompressionAlgorithmType }
     *     
     */
    public AttachmentCompressionAlgorithmType getAttachmentCompressionAlgorithm() {
        return attachmentCompressionAlgorithm;
    }

    /**
     * Sets the value of the attachmentCompressionAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentCompressionAlgorithmType }
     *     
     */
    public void setAttachmentCompressionAlgorithm(AttachmentCompressionAlgorithmType value) {
        this.attachmentCompressionAlgorithm = value;
    }

    /**
     * Gets the value of the attachmentFormat property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentFormatType }
     *     
     */
    public AttachmentFormatType getAttachmentFormat() {
        return attachmentFormat;
    }

    /**
     * Sets the value of the attachmentFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentFormatType }
     *     
     */
    public void setAttachmentFormat(AttachmentFormatType value) {
        this.attachmentFormat = value;
    }

    /**
     * Gets the value of the attachmentEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentEncodingType }
     *     
     */
    public AttachmentEncodingType getAttachmentEncoding() {
        return attachmentEncoding;
    }

    /**
     * Sets the value of the attachmentEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentEncodingType }
     *     
     */
    public void setAttachmentEncoding(AttachmentEncodingType value) {
        this.attachmentEncoding = value;
    }

    /**
     * Gets the value of the attachmentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachmentDescription() {
        return attachmentDescription;
    }

    /**
     * Sets the value of the attachmentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachmentDescription(String value) {
        this.attachmentDescription = value;
    }

    /**
     * Gets the value of the attachmentData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachmentData() {
        return attachmentData;
    }

    /**
     * Sets the value of the attachmentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachmentData(String value) {
        this.attachmentData = value;
    }

}
